import type { TileType } from './TileConfig';

export type Category = 'all' | 'payments' | 'deployments' | 'ci' | 'infrastructure' | 'generic' | 'analytics' | 'finance' | 'security' | 'social' | 'comms' | 'productivity';

export interface TileDefinition {
  type: TileType;
  label: string;
  provider: string;
  icon: string;
  category: Category;
  tags: string[];
  status: 'available' | 'coming-soon';
  description?: string;
}

export const CATEGORIES: Array<{ id: Category; icon: string; label: string }> = [
  { id: 'all',            icon: '⊞',  label: 'All'            },
  { id: 'payments',       icon: '💳',  label: 'Payments'       },
  { id: 'deployments',    icon: '🚀',  label: 'Deployments'    },
  { id: 'ci',             icon: '⚙️',  label: 'CI / Build'     },
  { id: 'infrastructure', icon: '🌥️',  label: 'Infrastructure' },
  { id: 'analytics',      icon: '📊',  label: 'Analytics'      },
  { id: 'finance',        icon: '💰',  label: 'Finance'        },
  { id: 'security',       icon: '🔒',  label: 'Security'       },
  { id: 'social',         icon: '💬',  label: 'Social'         },
  { id: 'comms',          icon: '📣',  label: 'Comms'          },
  { id: 'productivity',   icon: '📋',  label: 'Productivity'   },
  { id: 'generic',        icon: '🌐',  label: 'Generic'        },
];

export const TILE_REGISTRY: TileDefinition[] = [
  // ── Stripe ──────────────────────────────────────────────────────────────────
  {
    type: 'stripe-payments',
    label: 'Recent Payments',
    provider: 'Stripe',
    icon: '💳',
    category: 'payments',
    tags: ['stripe', 'payments', 'charges', 'transactions', 'financial'],
    status: 'available',
    description: 'Live feed of incoming charges',
  },
  {
    type: 'stripe-revenue',
    label: 'Revenue Trend',
    provider: 'Stripe',
    icon: '📈',
    category: 'payments',
    tags: ['stripe', 'revenue', 'mrr', 'chart', 'financial'],
    status: 'available',
    description: '30-day rolling revenue chart',
  },
  {
    type: 'stripe-orders',
    label: 'Orders',
    provider: 'Stripe',
    icon: '📦',
    category: 'payments',
    tags: ['stripe', 'orders', 'checkout'],
    status: 'available',
    description: 'Recent checkout orders',
  },
  {
    type: 'stripe-subscriptions',
    label: 'Subscriptions',
    provider: 'Stripe',
    icon: '🔄',
    category: 'payments',
    tags: ['stripe', 'subscriptions', 'recurring', 'billing'],
    status: 'available',
    description: 'Active and churned subscriptions',
  },
  {
    type: 'stripe-customers',
    label: 'Customers',
    provider: 'Stripe',
    icon: '👥',
    category: 'payments',
    tags: ['stripe', 'customers', 'users'],
    status: 'available',
    description: 'Customer list and activity',
  },
  {
    type: 'stripe-invoices',
    label: 'Invoices',
    provider: 'Stripe',
    icon: '🧾',
    category: 'payments',
    tags: ['stripe', 'invoices', 'billing', 'financial'],
    status: 'available',
    description: 'Paid and outstanding invoices',
  },
  {
    type: 'stripe-refunds',
    label: 'Refunds',
    provider: 'Stripe',
    icon: '↩️',
    category: 'payments',
    tags: ['stripe', 'refunds', 'disputes', 'financial'],
    status: 'available',
    description: 'Recent refunds and disputes',
  },
  {
    type: 'stripe-products',
    label: 'Products',
    provider: 'Stripe',
    icon: '🏷️',
    category: 'payments',
    tags: ['stripe', 'products', 'catalog', 'prices'],
    status: 'available',
    description: 'Product catalog and prices',
  },
  {
    type: 'stripe-webhooks',
    label: 'Webhook Events',
    provider: 'Stripe',
    icon: '🔔',
    category: 'payments',
    tags: ['stripe', 'webhooks', 'events'],
    status: 'available',
    description: 'Stripe webhook event log',
  },
  // ── PayPal ───────────────────────────────────────────────────────────────────
  {
    type: 'paypal-transactions',
    label: 'Transactions',
    provider: 'PayPal',
    icon: '🅿️',
    category: 'payments',
    tags: ['paypal', 'transactions', 'payments', 'financial'],
    status: 'available',
    description: 'PayPal transaction history',
  },
  // ── GitHub ───────────────────────────────────────────────────────────────────
  {
    type: 'github-actions',
    label: 'Workflow Runs',
    provider: 'GitHub',
    icon: '🐙',
    category: 'ci',
    tags: ['github', 'actions', 'ci', 'workflows', 'builds', 'pipelines'],
    status: 'available',
    description: 'GitHub Actions workflow runs',
  },
  // ── Cloudflare ───────────────────────────────────────────────────────────────
  {
    type: 'cloudflare-pages',
    label: 'Pages Deployments',
    provider: 'Cloudflare',
    icon: '🌥️',
    category: 'deployments',
    tags: ['cloudflare', 'pages', 'deployments', 'hosting'],
    status: 'available',
    description: 'Cloudflare Pages deploy history',
  },
  {
    type: 'cloudflare-functions',
    label: 'Workers Scripts',
    provider: 'Cloudflare',
    icon: '⚡',
    category: 'infrastructure',
    tags: ['cloudflare', 'workers', 'functions', 'serverless', 'edge'],
    status: 'available',
    description: 'Cloudflare Workers deployments',
  },
  // ── Vercel ───────────────────────────────────────────────────────────────────
  {
    type: 'vercel-deployments',
    label: 'Deployments',
    provider: 'Vercel',
    icon: '▲',
    category: 'deployments',
    tags: ['vercel', 'deployments', 'hosting', 'frontend'],
    status: 'available',
    description: 'Vercel project deployments',
  },
  // ── Netlify ──────────────────────────────────────────────────────────────────
  {
    type: 'netlify-deployments',
    label: 'Deployments',
    provider: 'Netlify',
    icon: '◆',
    category: 'deployments',
    tags: ['netlify', 'deployments', 'hosting', 'frontend'],
    status: 'available',
    description: 'Netlify site deployments',
  },
  // ── CircleCI ────────────────────────────────────────────────────────────────
  {
    type: 'circleci-pipelines',
    label: 'Pipelines',
    provider: 'CircleCI',
    icon: '🔵',
    category: 'ci',
    tags: ['circleci', 'ci', 'pipelines', 'builds', 'workflows'],
    status: 'available',
    description: 'CircleCI pipeline runs',
  },
  {
    type: 'circleci-insights',
    label: 'Insights',
    provider: 'CircleCI',
    icon: '📉',
    category: 'ci',
    tags: ['circleci', 'ci', 'insights', 'metrics', 'success-rate'],
    status: 'available',
    description: 'CircleCI workflow success rates and duration trends',
  },
  // ── Travis CI ────────────────────────────────────────────────────────────────
  {
    type: 'travis-builds',
    label: 'Builds',
    provider: 'Travis CI',
    icon: '🏗️',
    category: 'ci',
    tags: ['travis', 'ci', 'builds', 'pipelines'],
    status: 'available',
    description: 'Travis CI build results',
  },
  // ── Bitrise ──────────────────────────────────────────────────────────────────
  {
    type: 'bitrise-builds',
    label: 'Builds',
    provider: 'Bitrise',
    icon: '📱',
    category: 'ci',
    tags: ['bitrise', 'ci', 'mobile', 'builds', 'ios', 'android'],
    status: 'available',
    description: 'Bitrise mobile CI builds',
  },
  // ── SonarQube ────────────────────────────────────────────────────────────────
  {
    type: 'sonarqube-quality',
    label: 'Quality Gates',
    provider: 'SonarQube',
    icon: '🔍',
    category: 'ci',
    tags: ['sonarqube', 'quality', 'code-quality', 'gates', 'analysis'],
    status: 'available',
    description: 'SonarQube project quality gate status',
  },
  {
    type: 'sonarqube-measures',
    label: 'Code Measures',
    provider: 'SonarQube',
    icon: '📏',
    category: 'ci',
    tags: ['sonarqube', 'measures', 'coverage', 'bugs', 'vulnerabilities'],
    status: 'available',
    description: 'Code metrics: bugs, coverage, technical debt',
  },
  {
    type: 'sonarqube-issues',
    label: 'Issues',
    provider: 'SonarQube',
    icon: '⚠️',
    category: 'ci',
    tags: ['sonarqube', 'issues', 'code-smells', 'security-hotspots'],
    status: 'available',
    description: 'SonarQube code issues list',
  },
  // ── Azure DevOps ─────────────────────────────────────────────────────────────
  {
    type: 'azuredevops-pipelines',
    label: 'Pipelines',
    provider: 'Azure DevOps',
    icon: '🔷',
    category: 'ci',
    tags: ['azure', 'devops', 'pipelines', 'ci', 'builds'],
    status: 'available',
    description: 'Azure DevOps pipeline runs',
  },
  {
    type: 'azuredevops-releases',
    label: 'Releases',
    provider: 'Azure DevOps',
    icon: '📦',
    category: 'ci',
    tags: ['azure', 'devops', 'releases', 'deployments'],
    status: 'available',
    description: 'Azure DevOps release environments',
  },
  {
    type: 'azuredevops-workitems',
    label: 'Work Items',
    provider: 'Azure DevOps',
    icon: '📋',
    category: 'productivity',
    tags: ['azure', 'devops', 'work-items', 'boards', 'tasks'],
    status: 'available',
    description: 'Azure Boards work items',
  },
  // ── Docker Hub ───────────────────────────────────────────────────────────────
  {
    type: 'dockerhub-repositories',
    label: 'Repositories',
    provider: 'Docker Hub',
    icon: '🐳',
    category: 'infrastructure',
    tags: ['docker', 'hub', 'containers', 'images', 'registry'],
    status: 'available',
    description: 'Docker Hub image repositories',
  },
  {
    type: 'dockerhub-tags',
    label: 'Image Tags',
    provider: 'Docker Hub',
    icon: '🏷️',
    category: 'infrastructure',
    tags: ['docker', 'hub', 'tags', 'images', 'versions'],
    status: 'available',
    description: 'Docker image tag list',
  },
  // ── npm Registry ─────────────────────────────────────────────────────────────
  {
    type: 'npm-downloads',
    label: 'Downloads',
    provider: 'npm',
    icon: '📦',
    category: 'analytics',
    tags: ['npm', 'downloads', 'packages', 'registry', 'stats'],
    status: 'available',
    description: 'Weekly npm package download counts',
  },
  {
    type: 'npm-metadata',
    label: 'Package Info',
    provider: 'npm',
    icon: '📄',
    category: 'analytics',
    tags: ['npm', 'packages', 'metadata', 'version', 'license'],
    status: 'available',
    description: 'npm package metadata and version info',
  },
  // ── jsDelivr ─────────────────────────────────────────────────────────────────
  {
    type: 'jsdelivr-hits',
    label: 'CDN Hits',
    provider: 'jsDelivr',
    icon: '⚡',
    category: 'analytics',
    tags: ['jsdelivr', 'cdn', 'hits', 'bandwidth', 'stats'],
    status: 'available',
    description: 'jsDelivr CDN hit statistics',
  },
  {
    type: 'jsdelivr-versions',
    label: 'Package Versions',
    provider: 'jsDelivr',
    icon: '🔢',
    category: 'analytics',
    tags: ['jsdelivr', 'cdn', 'versions', 'packages'],
    status: 'available',
    description: 'jsDelivr package version listing',
  },
  // ── WakaTime ─────────────────────────────────────────────────────────────────
  {
    type: 'wakatime-summary',
    label: 'Coding Time',
    provider: 'WakaTime',
    icon: '⏱️',
    category: 'productivity',
    tags: ['wakatime', 'coding', 'time', 'productivity', 'stats'],
    status: 'available',
    description: 'Daily coding time summary',
  },
  {
    type: 'wakatime-languages',
    label: 'Languages',
    provider: 'WakaTime',
    icon: '💻',
    category: 'productivity',
    tags: ['wakatime', 'languages', 'coding', 'breakdown'],
    status: 'available',
    description: 'Coding time breakdown by language',
  },
  {
    type: 'wakatime-projects',
    label: 'Projects',
    provider: 'WakaTime',
    icon: '🗂️',
    category: 'productivity',
    tags: ['wakatime', 'projects', 'coding', 'time'],
    status: 'available',
    description: 'Coding time per project',
  },
  // ── Clockify ─────────────────────────────────────────────────────────────────
  {
    type: 'clockify-time-entries',
    label: 'Time Entries',
    provider: 'Clockify',
    icon: '🕐',
    category: 'productivity',
    tags: ['clockify', 'time-tracking', 'entries', 'productivity'],
    status: 'available',
    description: 'Clockify time entry log',
  },
  {
    type: 'clockify-projects',
    label: 'Projects',
    provider: 'Clockify',
    icon: '📁',
    category: 'productivity',
    tags: ['clockify', 'projects', 'time-tracking'],
    status: 'available',
    description: 'Clockify project time summary',
  },
  // ── Linear ───────────────────────────────────────────────────────────────────
  {
    type: 'linear-issues',
    label: 'Issues',
    provider: 'Linear',
    icon: '⬡',
    category: 'productivity',
    tags: ['linear', 'issues', 'tasks', 'backlog', 'project-management'],
    status: 'available',
    description: 'Linear team issues',
  },
  {
    type: 'linear-cycles',
    label: 'Cycles',
    provider: 'Linear',
    icon: '🔄',
    category: 'productivity',
    tags: ['linear', 'cycles', 'sprints', 'progress'],
    status: 'available',
    description: 'Linear cycle progress and completion',
  },
  {
    type: 'linear-teams',
    label: 'Teams',
    provider: 'Linear',
    icon: '👥',
    category: 'productivity',
    tags: ['linear', 'teams', 'members'],
    status: 'available',
    description: 'Linear team overview',
  },
  // ── Jira ─────────────────────────────────────────────────────────────────────
  {
    type: 'jira-issues',
    label: 'Issues',
    provider: 'Jira',
    icon: '🐞',
    category: 'productivity',
    tags: ['jira', 'issues', 'tasks', 'backlog', 'project-management'],
    status: 'available',
    description: 'Jira issue tracker',
  },
  {
    type: 'jira-sprint',
    label: 'Sprint',
    provider: 'Jira',
    icon: '🏃',
    category: 'productivity',
    tags: ['jira', 'sprint', 'agile', 'burndown'],
    status: 'available',
    description: 'Active sprint burndown',
  },
  {
    type: 'jira-projects',
    label: 'Projects',
    provider: 'Jira',
    icon: '📂',
    category: 'productivity',
    tags: ['jira', 'projects', 'boards'],
    status: 'available',
    description: 'Jira project list',
  },
  // ── Slack ─────────────────────────────────────────────────────────────────────
  {
    type: 'slack-messages',
    label: 'Messages',
    provider: 'Slack',
    icon: '💬',
    category: 'comms',
    tags: ['slack', 'messages', 'chat', 'channels'],
    status: 'available',
    description: 'Recent Slack channel messages',
  },
  {
    type: 'slack-workspace-stats',
    label: 'Workspace',
    provider: 'Slack',
    icon: '🏢',
    category: 'comms',
    tags: ['slack', 'workspace', 'members', 'stats'],
    status: 'available',
    description: 'Slack workspace member and channel stats',
  },
  // ── Discord ──────────────────────────────────────────────────────────────────
  {
    type: 'discord-server-stats',
    label: 'Server Stats',
    provider: 'Discord',
    icon: '🎮',
    category: 'comms',
    tags: ['discord', 'server', 'members', 'online'],
    status: 'available',
    description: 'Discord server member and activity stats',
  },
  {
    type: 'discord-channels',
    label: 'Channels',
    provider: 'Discord',
    icon: '📢',
    category: 'comms',
    tags: ['discord', 'channels', 'server'],
    status: 'available',
    description: 'Discord text channel list',
  },
  // ── Mailchimp ────────────────────────────────────────────────────────────────
  {
    type: 'mailchimp-campaigns',
    label: 'Campaigns',
    provider: 'Mailchimp',
    icon: '📧',
    category: 'comms',
    tags: ['mailchimp', 'campaigns', 'email', 'marketing'],
    status: 'available',
    description: 'Mailchimp email campaigns with open/click rates',
  },
  {
    type: 'mailchimp-audience',
    label: 'Audience',
    provider: 'Mailchimp',
    icon: '📨',
    category: 'comms',
    tags: ['mailchimp', 'audience', 'subscribers', 'list'],
    status: 'available',
    description: 'Mailchimp audience / subscriber stats',
  },
  // ── Google Analytics 4 ───────────────────────────────────────────────────────
  {
    type: 'ga4-sessions-trend',
    label: 'Sessions Trend',
    provider: 'Google Analytics',
    icon: '📈',
    category: 'analytics',
    tags: ['ga4', 'analytics', 'sessions', 'trend', 'google'],
    status: 'available',
    description: '7-day session trend chart',
  },
  {
    type: 'ga4-top-pages',
    label: 'Top Pages',
    provider: 'Google Analytics',
    icon: '📰',
    category: 'analytics',
    tags: ['ga4', 'analytics', 'pages', 'pageviews', 'google'],
    status: 'available',
    description: 'Top pages by pageviews',
  },
  {
    type: 'ga4-traffic-sources',
    label: 'Traffic Sources',
    provider: 'Google Analytics',
    icon: '🌐',
    category: 'analytics',
    tags: ['ga4', 'analytics', 'traffic', 'sources', 'google'],
    status: 'available',
    description: 'Traffic source breakdown',
  },
  // ── Instatus ─────────────────────────────────────────────────────────────────
  {
    type: 'instatus-overview',
    label: 'Status Page',
    provider: 'Instatus',
    icon: '🟢',
    category: 'analytics',
    tags: ['instatus', 'status', 'uptime', 'components'],
    status: 'available',
    description: 'Service status page overview',
  },
  {
    type: 'instatus-incidents',
    label: 'Incidents',
    provider: 'Instatus',
    icon: '🚨',
    category: 'analytics',
    tags: ['instatus', 'incidents', 'outages', 'downtime'],
    status: 'available',
    description: 'Incident history and active issues',
  },
  // ── HackerNews ───────────────────────────────────────────────────────────────
  {
    type: 'hn-top-stories',
    label: 'Top Stories',
    provider: 'HackerNews',
    icon: '🦊',
    category: 'social',
    tags: ['hackernews', 'hn', 'stories', 'news', 'tech'],
    status: 'available',
    description: 'HackerNews top stories feed',
  },
  {
    type: 'hn-mentions',
    label: 'Keyword Monitor',
    provider: 'HackerNews',
    icon: '🔎',
    category: 'social',
    tags: ['hackernews', 'hn', 'mentions', 'keywords', 'monitoring'],
    status: 'available',
    description: 'HN stories matching your keywords',
  },
  // ── Alpha Vantage ────────────────────────────────────────────────────────────
  {
    type: 'alphavantage-quotes',
    label: 'Stock Quotes',
    provider: 'Alpha Vantage',
    icon: '📊',
    category: 'finance',
    tags: ['alphavantage', 'stocks', 'quotes', 'finance', 'market'],
    status: 'available',
    description: 'Real-time stock quotes',
  },
  {
    type: 'alphavantage-sparklines',
    label: 'Price Sparklines',
    provider: 'Alpha Vantage',
    icon: '📉',
    category: 'finance',
    tags: ['alphavantage', 'stocks', 'sparklines', 'price-history'],
    status: 'available',
    description: 'Stock price history sparklines',
  },
  {
    type: 'alphavantage-market-status',
    label: 'Market Status',
    provider: 'Alpha Vantage',
    icon: '🏙️',
    category: 'finance',
    tags: ['alphavantage', 'market', 'status', 'open', 'closed', 'exchanges'],
    status: 'available',
    description: 'Global market open/closed status by exchange',
  },
  {
    type: 'alphavantage-market-movers',
    label: 'Market Movers',
    provider: 'Alpha Vantage',
    icon: '🚀',
    category: 'finance',
    tags: ['alphavantage', 'stocks', 'gainers', 'losers', 'movers', 'active'],
    status: 'available',
    description: 'Top gainers, losers and most actively traded stocks',
  },
  {
    type: 'alphavantage-news-sentiment',
    label: 'News & Sentiment',
    provider: 'Alpha Vantage',
    icon: '📡',
    category: 'finance',
    tags: ['alphavantage', 'news', 'sentiment', 'bullish', 'bearish', 'market'],
    status: 'available',
    description: 'News feed with bullish/bearish sentiment scores',
  },
  {
    type: 'alphavantage-earnings',
    label: 'EPS Earnings',
    provider: 'Alpha Vantage',
    icon: '💰',
    category: 'finance',
    tags: ['alphavantage', 'earnings', 'eps', 'quarterly', 'stocks'],
    status: 'available',
    description: 'Quarterly and annual EPS earnings history',
  },
  {
    type: 'alphavantage-earnings-calendar',
    label: 'Earnings Calendar',
    provider: 'Alpha Vantage',
    icon: '📅',
    category: 'finance',
    tags: ['alphavantage', 'earnings', 'calendar', 'upcoming', 'eps'],
    status: 'available',
    description: 'Upcoming earnings reports for the next 3 months',
  },
  {
    type: 'alphavantage-fundamentals',
    label: 'Stock Fundamentals',
    provider: 'Alpha Vantage',
    icon: '🔬',
    category: 'finance',
    tags: ['alphavantage', 'fundamentals', 'pe', 'eps', 'market-cap', 'valuation'],
    status: 'available',
    description: 'Key fundamental metrics: P/E, EPS, market cap, 52W range',
  },
  {
    type: 'alphavantage-forex-rates',
    label: 'Forex Rates',
    provider: 'Alpha Vantage',
    icon: '💱',
    category: 'finance',
    tags: ['alphavantage', 'forex', 'currency', 'eur', 'usd', 'exchange-rate'],
    status: 'available',
    description: 'Currency exchange rates with mini price sparklines',
  },  {
    type: 'alphavantage-commodities',
    label: 'Commodities',
    provider: 'Alpha Vantage',
    icon: '🛢️',
    category: 'finance',
    tags: ['alphavantage', 'commodities', 'oil', 'gas', 'copper', 'wheat', 'wti', 'brent'],
    status: 'available',
    description: 'Global commodity prices: WTI, Brent, Natural Gas, Copper, Wheat',
  },
  {
    type: 'alphavantage-economic-indicators',
    label: 'Economic Indicators',
    provider: 'Alpha Vantage',
    icon: '📊',
    category: 'finance',
    tags: ['alphavantage', 'economy', 'gdp', 'inflation', 'cpi', 'unemployment', 'macro'],
    status: 'available',
    description: 'Key macroeconomic indicators: GDP, Inflation, Unemployment, CPI',
  },
  {
    type: 'alphavantage-insider-transactions',
    label: 'Insider Activity',
    provider: 'Alpha Vantage',
    icon: '🏗️',
    category: 'finance',
    tags: ['alphavantage', 'insider', 'transactions', 'premium', 'analytics'],
    status: 'available',
    description: 'Insider trading activity (requires Alpha Vantage Premium)',
  },  // ── CoinGecko ────────────────────────────────────────────────────────────────
  {
    type: 'coingecko-prices',
    label: 'Crypto Prices',
    provider: 'CoinGecko',
    icon: '🦎',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'prices', 'bitcoin', 'finance'],
    status: 'available',
    description: 'Live cryptocurrency prices',
  },
  {
    type: 'coingecko-global',
    label: 'Market Overview',
    provider: 'CoinGecko',
    icon: '🌍',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'market', 'global', 'market-cap'],
    status: 'available',
    description: 'Global crypto market stats',
  },  {
    type: 'coingecko-trending',
    label: 'Trending Coins',
    provider: 'CoinGecko',
    icon: '🔥',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'trending', 'popular'],
    status: 'available',
    description: 'Top 7 trending cryptocurrencies on CoinGecko',
  },
  {
    type: 'coingecko-price-chart',
    label: 'Crypto Price Chart',
    provider: 'CoinGecko',
    icon: '📈',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'chart', 'price', 'sparkline'],
    status: 'available',
    description: '7-day price chart sparkline for configured cryptocurrencies',
  },
  {
    type: 'coingecko-defi-overview',
    label: 'DeFi Overview',
    provider: 'CoinGecko',
    icon: '🏦',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'defi', 'tvl', 'dominance'],
    status: 'available',
    description: 'DeFi market overview: total TVL, DeFi dominance, top protocol',
  },
  {
    type: 'coingecko-categories',
    label: 'Coin Categories',
    provider: 'CoinGecko',
    icon: '🏷️',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'categories', 'sector', 'market-cap'],
    status: 'available',
    description: 'Top cryptocurrency categories by market cap and 24h performance',
  },
  {
    type: 'coingecko-exchanges',
    label: 'Crypto Exchanges',
    provider: 'CoinGecko',
    icon: '🏛️',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'exchanges', 'volume', 'trust'],
    status: 'available',
    description: 'Top 10 crypto exchanges by trust score and trading volume',
  },
  {
    type: 'coingecko-coin-detail',
    label: 'Coin Detail',
    provider: 'CoinGecko',
    icon: '🪙',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'detail', 'coin', 'stats'],
    status: 'available',
    description: 'Detailed stats for a cryptocurrency: price, ATH, market cap, description',
  },  // ── Finnhub ──────────────────────────────────────────────────────────────────
  {
    type: 'finnhub-quotes',
    label: 'Market Quotes',
    provider: 'Finnhub',
    icon: '💹',
    category: 'finance',
    tags: ['finnhub', 'stocks', 'quotes', 'market', 'finance'],
    status: 'available',
    description: 'Real-time stock/forex quotes from Finnhub',
  },
  {
    type: 'finnhub-news',
    label: 'Financial News',
    provider: 'Finnhub',
    icon: '📰',
    category: 'finance',
    tags: ['finnhub', 'news', 'financial', 'sentiment'],
    status: 'available',
    description: 'Company and market news with sentiment',
  },
  {
    type: 'finnhub-company-news',
    label: 'Company News',
    provider: 'Finnhub',
    icon: '🗞️',
    category: 'finance',
    tags: ['finnhub', 'news', 'company', 'stocks'],
    status: 'available',
    description: 'Latest company news for your configured symbols',
  },
  {
    type: 'finnhub-market-news',
    label: 'Market News',
    provider: 'Finnhub',
    icon: '📡',
    category: 'finance',
    tags: ['finnhub', 'news', 'market', 'forex', 'crypto', 'general'],
    status: 'available',
    description: 'Market news by category: general, forex, crypto',
  },
  {
    type: 'finnhub-earnings-calendar',
    label: 'Earnings Calendar (Finnhub)',
    provider: 'Finnhub',
    icon: '📅',
    category: 'finance',
    tags: ['finnhub', 'earnings', 'calendar', 'upcoming', 'eps'],
    status: 'available',
    description: 'Upcoming earnings releases from Finnhub for the next 30 days',
  },
  {
    type: 'finnhub-earnings-surprises',
    label: 'Earnings Surprises',
    provider: 'Finnhub',
    icon: '💡',
    category: 'finance',
    tags: ['finnhub', 'earnings', 'surprise', 'eps', 'actual', 'estimate'],
    status: 'available',
    description: 'Quarterly EPS actual vs estimate with surprise percentage',
  },
  {
    type: 'finnhub-analyst-consensus',
    label: 'Analyst Consensus',
    provider: 'Finnhub',
    icon: '🎯',
    category: 'finance',
    tags: ['finnhub', 'analyst', 'recommendation', 'buy', 'sell'],
    status: 'available',
    description: 'Analyst buy/hold/sell recommendations consensus by symbol',
  },
  {
    type: 'finnhub-fundamentals',
    label: 'Stock Fundamentals (Finnhub)',
    provider: 'Finnhub',
    icon: '📊',
    category: 'finance',
    tags: ['finnhub', 'fundamentals', 'pe', 'eps', 'roe', 'beta', 'metrics'],
    status: 'available',
    description: 'Key fundamental metrics from Finnhub: P/E, P/B, ROA, ROE, beta',
  },
  {
    type: 'finnhub-market-status',
    label: 'Market Status (Finnhub)',
    provider: 'Finnhub',
    icon: '🟢',
    category: 'finance',
    tags: ['finnhub', 'market', 'status', 'open', 'closed', 'exchange'],
    status: 'available',
    description: 'Real-time market open/closed status for major exchanges',
  },
  {
    type: 'finnhub-insider-transactions',
    label: 'Insider Transactions',
    provider: 'Finnhub',
    icon: '🏦',
    category: 'finance',
    tags: ['finnhub', 'insider', 'transactions', 'buy', 'sell', 'schedule-13'],
    status: 'available',
    description: 'Insider buy/sell transactions from SEC filings',
  },
  {
    type: 'finnhub-insider-sentiment',
    label: 'Insider Sentiment',
    provider: 'Finnhub',
    icon: '🧭',
    category: 'finance',
    tags: ['finnhub', 'insider', 'sentiment', 'mspr', 'bullish', 'bearish'],
    status: 'available',
    description: 'Monthly insider sentiment (MSPR) gauge — positive = bullish insiders',
  },
  {
    type: 'finnhub-ipo-calendar',
    label: 'IPO Calendar',
    provider: 'Finnhub',
    icon: '🚀',
    category: 'finance',
    tags: ['finnhub', 'ipo', 'listing', 'calendar', 'upcoming'],
    status: 'available',
    description: 'Upcoming IPO listings for the next 30 days from Finnhub',
  },
  {
    type: 'finnhub-sec-filings',
    label: 'SEC Filings',
    provider: 'Finnhub',
    icon: '📄',
    category: 'finance',
    tags: ['finnhub', 'sec', 'filings', '10-K', '10-Q', '8-K', 'annual', 'quarterly'],
    status: 'available',
    description: 'Recent SEC filings (10-K, 10-Q, 8-K) with download links',
  },
  {
    type: 'finnhub-company-profile',
    label: 'Company Profile',
    provider: 'Finnhub',
    icon: '🏢',
    category: 'finance',
    tags: ['finnhub', 'company', 'profile', 'logo', 'sector', 'exchange'],
    status: 'available',
    description: 'Company logo, sector, exchange, IPO date, and key info',
  },
  // ── Plaid ────────────────────────────────────────────────────────────────────
  {
    type: 'plaid-balances',
    label: 'Account Balances',
    provider: 'Plaid',
    icon: '🏦',
    category: 'finance',
    tags: ['plaid', 'bank', 'balances', 'accounts', 'finance'],
    status: 'available',
    description: 'Bank account balances via Plaid',
  },
  {
    type: 'plaid-transactions',
    label: 'Transactions',
    provider: 'Plaid',
    icon: '💸',
    category: 'finance',
    tags: ['plaid', 'bank', 'transactions', 'spending', 'finance'],
    status: 'available',
    description: 'Recent bank transactions',
  },
  {
    type: 'plaid-investment-portfolio',
    label: 'Investment Portfolio',
    provider: 'Plaid',
    icon: '📈',
    category: 'finance',
    tags: ['plaid', 'investments', 'portfolio', 'holdings', 'finance'],
    status: 'available',
    description: 'Investment holdings with gain/loss tracking',
  },
  {
    type: 'plaid-investment-transactions',
    label: 'Investment Transactions',
    provider: 'Plaid',
    icon: '🔄',
    category: 'finance',
    tags: ['plaid', 'investments', 'transactions', 'trading', 'finance'],
    status: 'available',
    description: 'Recent investment transactions (buy/sell/dividend)',
  },
  {
    type: 'plaid-liabilities-overview',
    label: 'Liabilities Overview',
    provider: 'Plaid',
    icon: '💳',
    category: 'finance',
    tags: ['plaid', 'liabilities', 'debt', 'credit', 'mortgage', 'finance'],
    status: 'available',
    description: 'Total liabilities breakdown by type',
  },
  {
    type: 'plaid-credit-card-details',
    label: 'Credit Card Details',
    provider: 'Plaid',
    icon: '💳',
    category: 'finance',
    tags: ['plaid', 'credit', 'cards', 'utilization', 'finance'],
    status: 'available',
    description: 'Credit card utilization, balances and payment info',
  },
  {
    type: 'plaid-mortgage-tracker',
    label: 'Mortgage Tracker',
    provider: 'Plaid',
    icon: '🏠',
    category: 'finance',
    tags: ['plaid', 'mortgage', 'home', 'loan', 'finance'],
    status: 'available',
    description: 'Mortgage balance, rate, and payment schedule',
  },
  {
    type: 'plaid-statements',
    label: 'Statements',
    provider: 'Plaid',
    icon: '📄',
    category: 'finance',
    tags: ['plaid', 'statements', 'bank', 'documents', 'finance'],
    status: 'available',
    description: 'Bank and credit account statements',
  },
  // ── HIBP ─────────────────────────────────────────────────────────────────────
  {
    type: 'hibp-breach-status',
    label: 'Breach Status',
    provider: 'HaveIBeenPwned',
    icon: '🔐',
    category: 'security',
    tags: ['hibp', 'breach', 'security', 'email', 'pwned'],
    status: 'available',
    description: 'Check emails for data breaches',
  },
  {
    type: 'hibp-recent-breaches',
    label: 'Recent Breaches',
    provider: 'HaveIBeenPwned',
    icon: '⚠️',
    category: 'security',
    tags: ['hibp', 'breaches', 'security', 'recent'],
    status: 'available',
    description: 'Recently published data breaches',
  },
  // ── VirusTotal ───────────────────────────────────────────────────────────────
  {
    type: 'virustotal-domain-threats',
    label: 'Domain Threats',
    provider: 'VirusTotal',
    icon: '🦠',
    category: 'security',
    tags: ['virustotal', 'domain', 'threats', 'malware', 'security'],
    status: 'available',
    description: 'Domain threat analysis from VirusTotal',
  },
  {
    type: 'virustotal-url-scan',
    label: 'URL Scanner',
    provider: 'VirusTotal',
    icon: '🔗',
    category: 'security',
    tags: ['virustotal', 'url', 'scan', 'threat', 'security'],
    status: 'available',
    description: 'Submit and view URL threat scans',
  },
  // ── Shodan ───────────────────────────────────────────────────────────────────
  {
    type: 'shodan-exposed-services',
    label: 'Exposed Services',
    provider: 'Shodan',
    icon: '🌐',
    category: 'security',
    tags: ['shodan', 'exposed', 'services', 'ports', 'security', 'iot'],
    status: 'available',
    description: 'Internet-exposed services and ports',
  },
  {
    type: 'shodan-vuln-summary',
    label: 'Vulnerability Summary',
    provider: 'Shodan',
    icon: '💀',
    category: 'security',
    tags: ['shodan', 'cve', 'vulnerabilities', 'security'],
    status: 'available',
    description: 'CVE vulnerability summary from Shodan',
  },
  // ── WooCommerce ──────────────────────────────────────────────────────────────
  {
    type: 'woocommerce-orders',
    label: 'Orders',
    provider: 'WooCommerce',
    icon: '🛒',
    category: 'payments',
    tags: ['woocommerce', 'orders', 'ecommerce', 'wordpress'],
    status: 'available',
    description: 'WooCommerce order list',
  },
  {
    type: 'woocommerce-sales-summary',
    label: 'Sales Summary',
    provider: 'WooCommerce',
    icon: '💰',
    category: 'payments',
    tags: ['woocommerce', 'sales', 'revenue', 'ecommerce'],
    status: 'available',
    description: 'WooCommerce sales KPIs',
  },
  {
    type: 'woocommerce-top-sellers',
    label: 'Top Sellers',
    provider: 'WooCommerce',
    icon: '🏆',
    category: 'payments',
    tags: ['woocommerce', 'products', 'top-sellers', 'ecommerce'],
    status: 'available',
    description: 'Best-selling WooCommerce products',
  },
  // ── Shopify ──────────────────────────────────────────────────────────────────
  {
    type: 'shopify-orders',
    label: 'Orders',
    provider: 'Shopify',
    icon: '🛍️',
    category: 'payments',
    tags: ['shopify', 'orders', 'ecommerce'],
    status: 'available',
    description: 'Shopify order feed',
  },
  {
    type: 'shopify-products',
    label: 'Products',
    provider: 'Shopify',
    icon: '🏷️',
    category: 'payments',
    tags: ['shopify', 'products', 'catalog', 'ecommerce'],
    status: 'available',
    description: 'Shopify product catalog',
  },
  // ── Reddit ───────────────────────────────────────────────────────────────────
  {
    type: 'reddit-hot-posts',
    label: 'Hot Posts',
    provider: 'Reddit',
    icon: '🤖',
    category: 'social',
    tags: ['reddit', 'posts', 'hot', 'subreddit', 'community'],
    status: 'available',
    description: 'Reddit hot posts from monitored subreddits',
  },
  {
    type: 'reddit-keyword-monitor',
    label: 'Keyword Monitor',
    provider: 'Reddit',
    icon: '📡',
    category: 'social',
    tags: ['reddit', 'keywords', 'monitor', 'mentions', 'community'],
    status: 'available',
    description: 'Monitor Reddit for keyword mentions',
  },
  // ── Product Hunt ─────────────────────────────────────────────────────────────
  {
    type: 'producthunt-top-launches',
    label: 'Top Launches',
    provider: 'Product Hunt',
    icon: '🚀',
    category: 'social',
    tags: ['producthunt', 'launches', 'products', 'startups'],
    status: 'available',
    description: 'Top Product Hunt launches today',
  },

  // ── Generic ──────────────────────────────────────────────────────────────────
  {
    type: 'rss-feed',
    label: 'RSS Feed',
    provider: 'Custom',
    icon: '📰',
    category: 'generic',
    tags: ['rss', 'atom', 'feed', 'news', 'blog', 'custom'],
    status: 'available',
    description: 'Display any RSS or Atom feed',
  },
  {
    type: 'rest',
    label: 'REST API',
    provider: 'Custom',
    icon: '🌐',
    category: 'generic',
    tags: ['rest', 'api', 'http', 'json', 'custom'],
    status: 'available',
    description: 'Poll any HTTP/JSON endpoint',
  },
  {
    type: 'websocket',
    label: 'WebSocket',
    provider: 'Custom',
    icon: '🔌',
    category: 'generic',
    tags: ['websocket', 'ws', 'stream', 'realtime', 'custom'],
    status: 'available',
    description: 'Connect to a WebSocket stream',
  },
  {
    type: 'custom-api',
    label: 'Custom API',
    provider: 'Custom',
    icon: '⚡',
    category: 'generic',
    tags: ['custom', 'api', 'http', 'proxy', 'rest', 'post', 'json'],
    status: 'available',
    description: 'Proxy any HTTP API through the server — supports all methods, auth headers, and request body',
  },
  {
    type: 'graphql',
    label: 'GraphQL',
    provider: 'Generic',
    icon: '◈',
    category: 'generic',
    tags: ['graphql', 'api', 'query', 'json'],
    status: 'available',
    description: 'Query any GraphQL endpoint with custom queries, variables, and headers',
  },
];
