/**
 * Inserts new TileDefinitions into tileRegistry.ts before the Generic section.
 * Run with: bun scripts/patch-registry.mts
 */
import { readFileSync, writeFileSync } from 'fs';

const filePath = 'src/tiles/tileRegistry.ts';
const src = readFileSync(filePath, 'utf8');

// The new TileDefinitions block to insert before the Generic section
const insertions = `  // ── CircleCI ────────────────────────────────────────────────────────────────
  {
    type: 'circleci-pipelines',
    label: 'Pipelines',
    provider: 'CircleCI',
    icon: '🔵',
    category: 'ci',
    tags: ['circleci', 'ci', 'pipelines', 'builds', 'workflows'],
    status: 'available',
    description: 'CircleCI pipeline runs',
  },
  {
    type: 'circleci-insights',
    label: 'Insights',
    provider: 'CircleCI',
    icon: '📉',
    category: 'ci',
    tags: ['circleci', 'ci', 'insights', 'metrics', 'success-rate'],
    status: 'available',
    description: 'CircleCI workflow success rates and duration trends',
  },
  // ── Travis CI ────────────────────────────────────────────────────────────────
  {
    type: 'travis-builds',
    label: 'Builds',
    provider: 'Travis CI',
    icon: '🏗️',
    category: 'ci',
    tags: ['travis', 'ci', 'builds', 'pipelines'],
    status: 'available',
    description: 'Travis CI build results',
  },
  // ── Bitrise ──────────────────────────────────────────────────────────────────
  {
    type: 'bitrise-builds',
    label: 'Builds',
    provider: 'Bitrise',
    icon: '📱',
    category: 'ci',
    tags: ['bitrise', 'ci', 'mobile', 'builds', 'ios', 'android'],
    status: 'available',
    description: 'Bitrise mobile CI builds',
  },
  // ── SonarQube ────────────────────────────────────────────────────────────────
  {
    type: 'sonarqube-quality',
    label: 'Quality Gates',
    provider: 'SonarQube',
    icon: '🔍',
    category: 'ci',
    tags: ['sonarqube', 'quality', 'code-quality', 'gates', 'analysis'],
    status: 'available',
    description: 'SonarQube project quality gate status',
  },
  {
    type: 'sonarqube-measures',
    label: 'Code Measures',
    provider: 'SonarQube',
    icon: '📏',
    category: 'ci',
    tags: ['sonarqube', 'measures', 'coverage', 'bugs', 'vulnerabilities'],
    status: 'available',
    description: 'Code metrics: bugs, coverage, technical debt',
  },
  {
    type: 'sonarqube-issues',
    label: 'Issues',
    provider: 'SonarQube',
    icon: '⚠️',
    category: 'ci',
    tags: ['sonarqube', 'issues', 'code-smells', 'security-hotspots'],
    status: 'available',
    description: 'SonarQube code issues list',
  },
  // ── Azure DevOps ─────────────────────────────────────────────────────────────
  {
    type: 'azuredevops-pipelines',
    label: 'Pipelines',
    provider: 'Azure DevOps',
    icon: '🔷',
    category: 'ci',
    tags: ['azure', 'devops', 'pipelines', 'ci', 'builds'],
    status: 'available',
    description: 'Azure DevOps pipeline runs',
  },
  {
    type: 'azuredevops-releases',
    label: 'Releases',
    provider: 'Azure DevOps',
    icon: '📦',
    category: 'ci',
    tags: ['azure', 'devops', 'releases', 'deployments'],
    status: 'available',
    description: 'Azure DevOps release environments',
  },
  {
    type: 'azuredevops-workitems',
    label: 'Work Items',
    provider: 'Azure DevOps',
    icon: '📋',
    category: 'productivity',
    tags: ['azure', 'devops', 'work-items', 'boards', 'tasks'],
    status: 'available',
    description: 'Azure Boards work items',
  },
  // ── Docker Hub ───────────────────────────────────────────────────────────────
  {
    type: 'dockerhub-repositories',
    label: 'Repositories',
    provider: 'Docker Hub',
    icon: '🐳',
    category: 'infrastructure',
    tags: ['docker', 'hub', 'containers', 'images', 'registry'],
    status: 'available',
    description: 'Docker Hub image repositories',
  },
  {
    type: 'dockerhub-tags',
    label: 'Image Tags',
    provider: 'Docker Hub',
    icon: '🏷️',
    category: 'infrastructure',
    tags: ['docker', 'hub', 'tags', 'images', 'versions'],
    status: 'available',
    description: 'Docker image tag list',
  },
  // ── npm Registry ─────────────────────────────────────────────────────────────
  {
    type: 'npm-downloads',
    label: 'Downloads',
    provider: 'npm',
    icon: '📦',
    category: 'analytics',
    tags: ['npm', 'downloads', 'packages', 'registry', 'stats'],
    status: 'available',
    description: 'Weekly npm package download counts',
  },
  {
    type: 'npm-metadata',
    label: 'Package Info',
    provider: 'npm',
    icon: '📄',
    category: 'analytics',
    tags: ['npm', 'packages', 'metadata', 'version', 'license'],
    status: 'available',
    description: 'npm package metadata and version info',
  },
  // ── jsDelivr ─────────────────────────────────────────────────────────────────
  {
    type: 'jsdelivr-hits',
    label: 'CDN Hits',
    provider: 'jsDelivr',
    icon: '⚡',
    category: 'analytics',
    tags: ['jsdelivr', 'cdn', 'hits', 'bandwidth', 'stats'],
    status: 'available',
    description: 'jsDelivr CDN hit statistics',
  },
  {
    type: 'jsdelivr-versions',
    label: 'Package Versions',
    provider: 'jsDelivr',
    icon: '🔢',
    category: 'analytics',
    tags: ['jsdelivr', 'cdn', 'versions', 'packages'],
    status: 'available',
    description: 'jsDelivr package version listing',
  },
  // ── WakaTime ─────────────────────────────────────────────────────────────────
  {
    type: 'wakatime-summary',
    label: 'Coding Time',
    provider: 'WakaTime',
    icon: '⏱️',
    category: 'productivity',
    tags: ['wakatime', 'coding', 'time', 'productivity', 'stats'],
    status: 'available',
    description: 'Daily coding time summary',
  },
  {
    type: 'wakatime-languages',
    label: 'Languages',
    provider: 'WakaTime',
    icon: '💻',
    category: 'productivity',
    tags: ['wakatime', 'languages', 'coding', 'breakdown'],
    status: 'available',
    description: 'Coding time breakdown by language',
  },
  {
    type: 'wakatime-projects',
    label: 'Projects',
    provider: 'WakaTime',
    icon: '🗂️',
    category: 'productivity',
    tags: ['wakatime', 'projects', 'coding', 'time'],
    status: 'available',
    description: 'Coding time per project',
  },
  // ── Clockify ─────────────────────────────────────────────────────────────────
  {
    type: 'clockify-time-entries',
    label: 'Time Entries',
    provider: 'Clockify',
    icon: '🕐',
    category: 'productivity',
    tags: ['clockify', 'time-tracking', 'entries', 'productivity'],
    status: 'available',
    description: 'Clockify time entry log',
  },
  {
    type: 'clockify-projects',
    label: 'Projects',
    provider: 'Clockify',
    icon: '📁',
    category: 'productivity',
    tags: ['clockify', 'projects', 'time-tracking'],
    status: 'available',
    description: 'Clockify project time summary',
  },
  // ── Linear ───────────────────────────────────────────────────────────────────
  {
    type: 'linear-issues',
    label: 'Issues',
    provider: 'Linear',
    icon: '⬡',
    category: 'productivity',
    tags: ['linear', 'issues', 'tasks', 'backlog', 'project-management'],
    status: 'available',
    description: 'Linear team issues',
  },
  {
    type: 'linear-cycles',
    label: 'Cycles',
    provider: 'Linear',
    icon: '🔄',
    category: 'productivity',
    tags: ['linear', 'cycles', 'sprints', 'progress'],
    status: 'available',
    description: 'Linear cycle progress and completion',
  },
  {
    type: 'linear-teams',
    label: 'Teams',
    provider: 'Linear',
    icon: '👥',
    category: 'productivity',
    tags: ['linear', 'teams', 'members'],
    status: 'available',
    description: 'Linear team overview',
  },
  // ── Jira ─────────────────────────────────────────────────────────────────────
  {
    type: 'jira-issues',
    label: 'Issues',
    provider: 'Jira',
    icon: '🐞',
    category: 'productivity',
    tags: ['jira', 'issues', 'tasks', 'backlog', 'project-management'],
    status: 'available',
    description: 'Jira issue tracker',
  },
  {
    type: 'jira-sprint',
    label: 'Sprint',
    provider: 'Jira',
    icon: '🏃',
    category: 'productivity',
    tags: ['jira', 'sprint', 'agile', 'burndown'],
    status: 'available',
    description: 'Active sprint burndown',
  },
  {
    type: 'jira-projects',
    label: 'Projects',
    provider: 'Jira',
    icon: '📂',
    category: 'productivity',
    tags: ['jira', 'projects', 'boards'],
    status: 'available',
    description: 'Jira project list',
  },
  // ── Slack ─────────────────────────────────────────────────────────────────────
  {
    type: 'slack-messages',
    label: 'Messages',
    provider: 'Slack',
    icon: '💬',
    category: 'comms',
    tags: ['slack', 'messages', 'chat', 'channels'],
    status: 'available',
    description: 'Recent Slack channel messages',
  },
  {
    type: 'slack-workspace-stats',
    label: 'Workspace',
    provider: 'Slack',
    icon: '🏢',
    category: 'comms',
    tags: ['slack', 'workspace', 'members', 'stats'],
    status: 'available',
    description: 'Slack workspace member and channel stats',
  },
  // ── Discord ──────────────────────────────────────────────────────────────────
  {
    type: 'discord-server-stats',
    label: 'Server Stats',
    provider: 'Discord',
    icon: '🎮',
    category: 'comms',
    tags: ['discord', 'server', 'members', 'online'],
    status: 'available',
    description: 'Discord server member and activity stats',
  },
  {
    type: 'discord-channels',
    label: 'Channels',
    provider: 'Discord',
    icon: '📢',
    category: 'comms',
    tags: ['discord', 'channels', 'server'],
    status: 'available',
    description: 'Discord text channel list',
  },
  // ── Mailchimp ────────────────────────────────────────────────────────────────
  {
    type: 'mailchimp-campaigns',
    label: 'Campaigns',
    provider: 'Mailchimp',
    icon: '📧',
    category: 'comms',
    tags: ['mailchimp', 'campaigns', 'email', 'marketing'],
    status: 'available',
    description: 'Mailchimp email campaigns with open/click rates',
  },
  {
    type: 'mailchimp-audience',
    label: 'Audience',
    provider: 'Mailchimp',
    icon: '📨',
    category: 'comms',
    tags: ['mailchimp', 'audience', 'subscribers', 'list'],
    status: 'available',
    description: 'Mailchimp audience / subscriber stats',
  },
  // ── Google Analytics 4 ───────────────────────────────────────────────────────
  {
    type: 'ga4-sessions-trend',
    label: 'Sessions Trend',
    provider: 'Google Analytics',
    icon: '📈',
    category: 'analytics',
    tags: ['ga4', 'analytics', 'sessions', 'trend', 'google'],
    status: 'available',
    description: '7-day session trend chart',
  },
  {
    type: 'ga4-top-pages',
    label: 'Top Pages',
    provider: 'Google Analytics',
    icon: '📰',
    category: 'analytics',
    tags: ['ga4', 'analytics', 'pages', 'pageviews', 'google'],
    status: 'available',
    description: 'Top pages by pageviews',
  },
  {
    type: 'ga4-traffic-sources',
    label: 'Traffic Sources',
    provider: 'Google Analytics',
    icon: '🌐',
    category: 'analytics',
    tags: ['ga4', 'analytics', 'traffic', 'sources', 'google'],
    status: 'available',
    description: 'Traffic source breakdown',
  },
  // ── Instatus ─────────────────────────────────────────────────────────────────
  {
    type: 'instatus-overview',
    label: 'Status Page',
    provider: 'Instatus',
    icon: '🟢',
    category: 'analytics',
    tags: ['instatus', 'status', 'uptime', 'components'],
    status: 'available',
    description: 'Service status page overview',
  },
  {
    type: 'instatus-incidents',
    label: 'Incidents',
    provider: 'Instatus',
    icon: '🚨',
    category: 'analytics',
    tags: ['instatus', 'incidents', 'outages', 'downtime'],
    status: 'available',
    description: 'Incident history and active issues',
  },
  // ── HackerNews ───────────────────────────────────────────────────────────────
  {
    type: 'hn-top-stories',
    label: 'Top Stories',
    provider: 'HackerNews',
    icon: '🦊',
    category: 'social',
    tags: ['hackernews', 'hn', 'stories', 'news', 'tech'],
    status: 'available',
    description: 'HackerNews top stories feed',
  },
  {
    type: 'hn-mentions',
    label: 'Keyword Monitor',
    provider: 'HackerNews',
    icon: '🔎',
    category: 'social',
    tags: ['hackernews', 'hn', 'mentions', 'keywords', 'monitoring'],
    status: 'available',
    description: 'HN stories matching your keywords',
  },
  // ── Alpha Vantage ────────────────────────────────────────────────────────────
  {
    type: 'alphavantage-quotes',
    label: 'Stock Quotes',
    provider: 'Alpha Vantage',
    icon: '📊',
    category: 'finance',
    tags: ['alphavantage', 'stocks', 'quotes', 'finance', 'market'],
    status: 'available',
    description: 'Real-time stock quotes',
  },
  {
    type: 'alphavantage-sparklines',
    label: 'Price Sparklines',
    provider: 'Alpha Vantage',
    icon: '📉',
    category: 'finance',
    tags: ['alphavantage', 'stocks', 'sparklines', 'price-history'],
    status: 'available',
    description: 'Stock price history sparklines',
  },
  // ── CoinGecko ────────────────────────────────────────────────────────────────
  {
    type: 'coingecko-prices',
    label: 'Crypto Prices',
    provider: 'CoinGecko',
    icon: '🦎',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'prices', 'bitcoin', 'finance'],
    status: 'available',
    description: 'Live cryptocurrency prices',
  },
  {
    type: 'coingecko-global',
    label: 'Market Overview',
    provider: 'CoinGecko',
    icon: '🌍',
    category: 'finance',
    tags: ['coingecko', 'crypto', 'market', 'global', 'market-cap'],
    status: 'available',
    description: 'Global crypto market stats',
  },
  // ── Finnhub ──────────────────────────────────────────────────────────────────
  {
    type: 'finnhub-quotes',
    label: 'Market Quotes',
    provider: 'Finnhub',
    icon: '💹',
    category: 'finance',
    tags: ['finnhub', 'stocks', 'quotes', 'market', 'finance'],
    status: 'available',
    description: 'Real-time stock/forex quotes from Finnhub',
  },
  {
    type: 'finnhub-news',
    label: 'Financial News',
    provider: 'Finnhub',
    icon: '📰',
    category: 'finance',
    tags: ['finnhub', 'news', 'financial', 'sentiment'],
    status: 'available',
    description: 'Company and market news with sentiment',
  },
  // ── Plaid ────────────────────────────────────────────────────────────────────
  {
    type: 'plaid-balances',
    label: 'Account Balances',
    provider: 'Plaid',
    icon: '🏦',
    category: 'finance',
    tags: ['plaid', 'bank', 'balances', 'accounts', 'finance'],
    status: 'available',
    description: 'Bank account balances via Plaid',
  },
  {
    type: 'plaid-transactions',
    label: 'Transactions',
    provider: 'Plaid',
    icon: '💸',
    category: 'finance',
    tags: ['plaid', 'bank', 'transactions', 'spending', 'finance'],
    status: 'available',
    description: 'Recent bank transactions',
  },
  // ── HIBP ─────────────────────────────────────────────────────────────────────
  {
    type: 'hibp-breach-status',
    label: 'Breach Status',
    provider: 'HaveIBeenPwned',
    icon: '🔐',
    category: 'security',
    tags: ['hibp', 'breach', 'security', 'email', 'pwned'],
    status: 'available',
    description: 'Check emails for data breaches',
  },
  {
    type: 'hibp-recent-breaches',
    label: 'Recent Breaches',
    provider: 'HaveIBeenPwned',
    icon: '⚠️',
    category: 'security',
    tags: ['hibp', 'breaches', 'security', 'recent'],
    status: 'available',
    description: 'Recently published data breaches',
  },
  // ── VirusTotal ───────────────────────────────────────────────────────────────
  {
    type: 'virustotal-domain-threats',
    label: 'Domain Threats',
    provider: 'VirusTotal',
    icon: '🦠',
    category: 'security',
    tags: ['virustotal', 'domain', 'threats', 'malware', 'security'],
    status: 'available',
    description: 'Domain threat analysis from VirusTotal',
  },
  {
    type: 'virustotal-url-scan',
    label: 'URL Scanner',
    provider: 'VirusTotal',
    icon: '🔗',
    category: 'security',
    tags: ['virustotal', 'url', 'scan', 'threat', 'security'],
    status: 'available',
    description: 'Submit and view URL threat scans',
  },
  // ── Shodan ───────────────────────────────────────────────────────────────────
  {
    type: 'shodan-exposed-services',
    label: 'Exposed Services',
    provider: 'Shodan',
    icon: '🌐',
    category: 'security',
    tags: ['shodan', 'exposed', 'services', 'ports', 'security', 'iot'],
    status: 'available',
    description: 'Internet-exposed services and ports',
  },
  {
    type: 'shodan-vuln-summary',
    label: 'Vulnerability Summary',
    provider: 'Shodan',
    icon: '💀',
    category: 'security',
    tags: ['shodan', 'cve', 'vulnerabilities', 'security'],
    status: 'available',
    description: 'CVE vulnerability summary from Shodan',
  },
  // ── WooCommerce ──────────────────────────────────────────────────────────────
  {
    type: 'woocommerce-orders',
    label: 'Orders',
    provider: 'WooCommerce',
    icon: '🛒',
    category: 'payments',
    tags: ['woocommerce', 'orders', 'ecommerce', 'wordpress'],
    status: 'available',
    description: 'WooCommerce order list',
  },
  {
    type: 'woocommerce-sales-summary',
    label: 'Sales Summary',
    provider: 'WooCommerce',
    icon: '💰',
    category: 'payments',
    tags: ['woocommerce', 'sales', 'revenue', 'ecommerce'],
    status: 'available',
    description: 'WooCommerce sales KPIs',
  },
  {
    type: 'woocommerce-top-sellers',
    label: 'Top Sellers',
    provider: 'WooCommerce',
    icon: '🏆',
    category: 'payments',
    tags: ['woocommerce', 'products', 'top-sellers', 'ecommerce'],
    status: 'available',
    description: 'Best-selling WooCommerce products',
  },
  // ── Shopify ──────────────────────────────────────────────────────────────────
  {
    type: 'shopify-orders',
    label: 'Orders',
    provider: 'Shopify',
    icon: '🛍️',
    category: 'payments',
    tags: ['shopify', 'orders', 'ecommerce'],
    status: 'available',
    description: 'Shopify order feed',
  },
  {
    type: 'shopify-products',
    label: 'Products',
    provider: 'Shopify',
    icon: '🏷️',
    category: 'payments',
    tags: ['shopify', 'products', 'catalog', 'ecommerce'],
    status: 'available',
    description: 'Shopify product catalog',
  },
  // ── Reddit ───────────────────────────────────────────────────────────────────
  {
    type: 'reddit-hot-posts',
    label: 'Hot Posts',
    provider: 'Reddit',
    icon: '🤖',
    category: 'social',
    tags: ['reddit', 'posts', 'hot', 'subreddit', 'community'],
    status: 'available',
    description: 'Reddit hot posts from monitored subreddits',
  },
  {
    type: 'reddit-keyword-monitor',
    label: 'Keyword Monitor',
    provider: 'Reddit',
    icon: '📡',
    category: 'social',
    tags: ['reddit', 'keywords', 'monitor', 'mentions', 'community'],
    status: 'available',
    description: 'Monitor Reddit for keyword mentions',
  },
  // ── Product Hunt ─────────────────────────────────────────────────────────────
  {
    type: 'producthunt-top-launches',
    label: 'Top Launches',
    provider: 'Product Hunt',
    icon: '🚀',
    category: 'social',
    tags: ['producthunt', 'launches', 'products', 'startups'],
    status: 'available',
    description: 'Top Product Hunt launches today',
  },
`;

// Find the Generic section comment (unique 7-char word "Generic" in a comment line)
const genericMarker = src.indexOf("'generic'");
// Actually we want the // ── Generic comment, not the CATEGORIES line
// The registry TILE_REGISTRY Generic section starts after the Netlify closing }
// We search for the pattern in lines
const lines = src.split('\n');
let insertLine = -1;
for (let i = 0; i < lines.length; i++) {
  // Looking for the Generic comment line in the TILE_REGISTRY area (not CATEGORIES)
  if (lines[i].includes('Generic') && lines[i].includes('//') && i > 100) {
    insertLine = i;
    break;
  }
}

if (insertLine === -1) {
  console.error('Could not find Generic section!');
  process.exit(1);
}

console.log(`Inserting before line ${insertLine + 1}: ${lines[insertLine].trim()}`);

// Insert the new definitions before the Generic section
lines.splice(insertLine, 0, insertions);
const result = lines.join('\n');
writeFileSync(filePath, result);
console.log('Done! Registry patched successfully.');
